/**
 * @author: 卓文理
 * @email : 531840344@qq.com
 * @desc  : 目录结构
 */

export default [
    {
        name: '审核系统',
        model: 'Review',
        id: 1,
        subMenus: [{
            id: 14,
            name: '主贴审核',
            path: '/review/posts'
        }, {
            id: 15,
            name: '妆品审核',
            path: '/review/goods'
        }, {
            id: 16,
            name: '评论审核',
            path: '/review/comments'
        }, {
            id: 17,
            name: '参照画审核',
            path: '/review/copies/list'
        }, {
            id: 18,
            name: '头像审核',
            path: '/review/avatars/list'
        }, {
            id: 19,
            name: '发帖申请审核',
            path: '/review/post-applications/list'
        }, {
            id: 20,
            name: '达人申请审核',
            path: '/review/talents/list'
        }, {
            id: 20,
            name: '达人信息审核',
            path: '/review/talent'
        }, {
            id: 94,
            name: '视频审核',
            path: 'review/videos'
        }, {
            id: 100,
            name: '背景图片审核',
            path: 'review/users-background'
        }, {
            id: 103,
            name: '直播报名审核',
            path: 'review/live'
        }]
    }, {
        name: '推荐系统',
        model: 'Featured',
        id: 2,
        subMenus: [{
            id: 21,
            name: '参照画的推荐',
            path: '/featured/copies'
        }, {
            id: 22,
            name: '首页帖子推荐',
            path: '/featured/posts'
        }, {
            id: 23,
            name: '首页教程推荐',
            path: '/featured/tutorials'
        }, {
            id: 24,
            name: '首页妆品推荐',
            path: '/featured/goods'
        }, {
            id: 25,
            name: '首页广告推荐',
            path: '/featured/banner/feeds'
        }, {
            id: 85,
            name: '首页话题推荐',
            path: '/featured/topics'
        }, {
            id: 87,
            name: '首页直播推荐',
            path: '/featured/live'
        }, {
            id: 26,
            name: '发现页妆品推荐',
            path: '/featured/recommend-goods'
        }, {
            id: 27,
            name: '专题推荐',
            path: '/featured/features'
        }, {
            id: 96,
            name: '发布妆品话题推荐',
            path: '/featured/topic-suggestions'
        }]
    }, {
        name: '分类管理',
        model: 'Categories',
        id: 3,
        subMenus: [{
            id: 28,
            name: '教程分类',
            path: '/categories/tutorial'
        }, {
            id: 29,
            name: '场景分类',
            path: '/categories/scene'
        }, {
            id: 30,
            name: '群体分类',
            path: '/categories/group'
        }, {
            id: 78,
            name: '专题分类',
            path: '/categories/feature'
        }]
    }, {
        name: '发布系统',
        model: 'Publishing',
        id: 4,
        subMenus: [{
            id: 31,
            name: '帖子发布',
            path: '/publishing/posts/create'
        }, {
            id: 31,
            name: '帖子列表',
            path: '/publishing/posts'
        }, {
            id: 32,
            name: '教程发布',
            path: '/publishing/tutorials/create'
        }, {
            id: 32,
            name: '教程列表',
            path: '/publishing/tutorials'
        }, {
            id: 33,
            name: '专题发布',
            path: '/publishing/feature/create'
        }, {
            id: 33,
            name: '专题列表',
            path: '/publishing/feature'
        }, {
            id: 71,
            name: '专题编辑器',
            path: '/publishing/editor'
        }, {
            id: 95,
            name: '贴纸管理',
            path: '/publishing/pasters'
        }, {
            id: 104,
            name: '链接管理',
            path: '/publishing/tutorials-link'
        }, {
            id: 105,
            name: '链接设置管理',
            path: '/publishing/tutorials-setting'
        }]
    }, {
        name: '回复系统',
        model: 'Comment',
        id: 5,
        subMenus: [{
            id: 34,
            name: '帖子列表',
            path: '/comment/posts'
        }, {
            id: 35,
            name: '教程列表',
            path: '/comment/tutorials'
        }, {
            id: 36,
            name: '试用列表',
            path: '/comment/trials'
        }, {
            id: 37,
            name: '妆品列表',
            path: '/comment/goods'
        }, {
            id: 38,
            name: '参照画的',
            path: '/comment/copies'
        }, {
            id: 39,
            name: '设置',
            path: '/comment/setting'
        }]
    }, {
        name: '试用管理',
        model: 'Trials',
        id: 6,
        subMenus: [{
            id: 40,
            name: '试用列表',
            path: '/trials/list'
        }, {
            id: 40,
            name: '添加试用',
            path: '/trials/list?action=add'
        }]
    }, {
        name: '品牌/妆品管理',
        model: 'Brand',
        id: 7,
        subMenus: [{
            id: 41,
            name: '品牌管理',
            path: '/brand/list'
        }, {
            id: 42,
            name: '妆品管理',
            path: '/brand/products'
        }, {
            id: 42,
            name: '未审核妆品',
            path: '/brand/products/no-review'
        }, {
            id: 43,
            name: '妆品导入',
            path: '/brand/import'
        }, {
            id: 86,
            name: '妆品绑定',
            path: '/brand/goods-bind'
        }, {
            id: 90,
            name: '品牌绑定',
            path: '/brand/brand-bind'
        }]
    }, {
        name: '用户管理',
        model: 'Users',
        id: 8,
        subMenus: [{
            id: 44,
            name: '用户列表',
            path: '/users/list'
        }, {
            id: 45,
            name: '用户分组',
            path: '/users/label'
        }, {
            id: 46,
            name: '用户统计',
            path: '/users/stats/all'
        }, {
            id: 47,
            name: '新增用户',
            path: '/users/list/create'
        }, {
            id: 48,
            name: '删除用户',
            path: '/users/del'
        }, {
            id: 49,
            name: '关注用户',
            path: '/users/follow'
        }, {
            id: 50,
            name: '地址查询',
            path: '/users/address'
        }]
    }, {
        name: '消息系统',
        model: 'Message',
        id: 9,
        subMenus: [{
            id: 51,
            name: '创建运营推送',
            path: '/message/operations/create'
        }, {
            id: 51,
            name: '运营推送列表',
            path: '/message/operations/index'
        }, {
            id: 51,
            name: '创建普通推送',
            path: '/message/pushs/create'
        }, {
            id: 51,
            name: '普通推送列表',
            path: '/message/pushs/index'
        }]
    }, {
        name: '积分系统',
        model: 'Point',
        id: 10,
        subMenus: [{
            id: 52,
            name: '普通积分兑换',
            path: '/points/list'
        }, {
            id: 97,
            name: 'M-idol积分兑换',
            path: '/points/drlist'
        }, {
            id: 52,
            name: '添加礼品',
            path: '/points/list/create'
        }, {
            id: 53,
            name: '手动积分',
            path: '/points/users'
        }, {
            id: 77,
            name: '积分黑名单',
            path: '/points/black'
        }, {
            id: 88,
            name: '积分统计',
            path: '/points/stats'
        }]
    }, {
        name: '运营管理',
        model: 'Operations',
        id: 11,
        subMenus: [{
            id: 54,
            name: '广告管理',
            path: '/operations/slides'
        }, {
            id: 55,
            name: '话题管理',
            path: '/operations/topics'
        }, {
            id: 56,
            name: '热门搜索',
            path: '/operations/search'
        }, {
            id: 57,
            name: '妆品发现页话题',
            path: '/operations/hot-topics'
        }, {
            id: 58,
            name: '启屏活动页',
            path: '/operations/start-activity-pages'
        }, {
            id: 59,
            name: '热门教程',
            path: '/operations/hot-tutorials'
        }, {
            id: 79,
            name: '运营话题管理',
            path: '/operations/topics/operation'
        }, {
            id: 80,
            name: '妆品类目管理',
            path: '/operations/topics/goods'
        }, {
            id: 81,
            name: '发现页类目推荐管理',
            path: '/operations/topics/recommend'
        }, {
            id: 82,
            name: '投票管理',
            path: '/operations/votes'
        }, {
            id: 83,
            name: '发现页推荐用户管理',
            path: '/operations/custom-users'
        }, {
            id: 80,
            name: '发现页配置',
            path: '/operations/custom-lists'
        }]
    }, {
        name: '直播管理',
        model: 'Live',
        id: 73,
        subMenus: [{
            id: 74,
            name: '直播列表',
            path: '/live/list'
        }, {
            id: 74,
            name: '创建直播',
            path: '/live/list/create'
        }, {
            id: 102,
            name: '回放列表',
            path: '/live/back/index'
        }]
    }, {
        name: '搜索管理',
        model: 'Search',
        id: 91,
        subMenus: [{
            id: 92,
            name: '页面跳转联想',
            path: '/search/skip'
        }, {
            id: 93,
            name: '搜索结果联想',
            path: '/search/result'
        }]
    }, {
        name: '设置',
        model: 'Settings',
        id: 12,
        subMenus: [{
            id: 84,
            name: '首页配置',
            path: '/settings/metadata'
        }, {
            id: 60,
            name: '预设文案',
            path: '/settings/words'
        }, {
            id: 61,
            name: '敏感词',
            path: '/settings/forbidden-words'
        }, {
            id: 62,
            name: '友情链接',
            path: '/settings/partner-links'
        }, {
            id: 63,
            name: '短链管理',
            path: '/settings/short-links'
        }, {
            id: 64,
            name: '失败任务管理',
            path: '/settings/failed'
        }, {
            id: 65,
            name: 'Hybrid包管理',
            path: '/settings/pkg'
        }, {
            id: 72,
            name: '修改密码',
            path: '/settings/password'
        }, {
            id: 75,
            name: '意见反馈',
            path: '/settings/feedback'
        }, {
            id: 76,
            name: '意见反馈设置',
            path: '/settings/feedback/setting'
        }]
    }, {
        name: '高级设置',
        model: 'Advanced',
        id: 13,
        subMenus: [{
            id: 66,
            name: 'iOS配置',
            path: '/advanced/ios-config'
        }, {
            id: 67,
            name: '子账户管理',
            path: '/advanced/admin'
        }]
    }
];
